//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_horarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_horarios()
        {
            this.tb_citas = new HashSet<tb_citas>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TerapeutaId { get; set; }
        public Nullable<int> SalonId { get; set; }
        public string DiaSemana { get; set; }
        public System.TimeSpan HoraInicio { get; set; }
        public System.TimeSpan HoraFin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_citas> tb_citas { get; set; }
        public virtual tb_salones tb_salones { get; set; }
        public virtual tb_terapeutas tb_terapeutas { get; set; }
    }
}
